/**
* Generated by LEA for Arma 3
* Version: 2.0.16
* Mon Mar 24 18:12:43 CET 2014
* Mission file name: Scenario.Altis
* Mission name: Scenario.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit unit_12_28
//Empty, nothing to do. unit unit_13_29
//Empty, nothing to do. unit Ghost
//Empty, nothing to do. unit One
//Empty, nothing to do. unit Two
//Empty, nothing to do. unit HB
//Empty, nothing to do. unit unit_37_67
//Empty, nothing to do. unit unit_37_68
//Empty, nothing to do. unit unit_37_69
//Empty, nothing to do. unit unit_37_70

/**
* Loadout for soldiers units
*/

if (player == Mortier_bipod) exitwith {
removeallweapons Mortier_bipod;
removeallassigneditems Mortier_bipod;
removeHeadgear Mortier_bipod;
removeBackpack Mortier_bipod;
removeVest Mortier_bipod;

Mortier_bipod addWeapon "ItemMap";
Mortier_bipod addWeapon "ItemWatch";
Mortier_bipod addWeapon "ItemCompass";
Mortier_bipod addWeapon "H_HelmetB_grass";
Mortier_bipod addWeapon "G_Sport_Checkered";
Mortier_bipod addWeapon "Rangefinder";
Mortier_bipod addBackpack "B_Mortar_01_support_F";
Mortier_bipod addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Mortier_bipod);
clearMagazineCargoGlobal (vestContainer Mortier_bipod);
clearWeaponCargoGlobal (vestContainer Mortier_bipod);
(vestContainer Mortier_bipod) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",5];
(vestContainer Mortier_bipod) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Mortier_bipod) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Mortier_bipod) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Mortier_bipod);
clearMagazineCargoGlobal (uniformContainer Mortier_bipod);
clearWeaponCargoGlobal (uniformContainer Mortier_bipod);
(uniformContainer Mortier_bipod) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Mortier_bipod) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Mortier_bipod) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Mortier_bipod addWeapon "arifle_MXC_F";
Mortier_bipod addPrimaryWeaponItem "acc_pointer_IR";
Mortier_bipod addPrimaryWeaponItem "optic_Aco";
(uniformContainer Mortier_bipod) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Mortier_bipod addWeapon "hgun_ACPC2_F";
Mortier_bipod addWeapon "ItemRadio";
Mortier_bipod selectWeapon (primaryWeapon Mortier_bipod);
};

if (player == Drone) exitwith {
removeallweapons Drone;
removeallassigneditems Drone;
removeHeadgear Drone;
removeBackpack Drone;
removeVest Drone;

Drone addWeapon "ItemMap";
Drone addWeapon "ItemWatch";
Drone addWeapon "ItemCompass";
Drone addWeapon "I_UavTerminal";
Drone addWeapon "H_HelmetB_grass";
Drone addWeapon "G_Sport_Checkered";
Drone addBackpack "B_UAV_01_backpack_F";
Drone addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Drone);
clearMagazineCargoGlobal (vestContainer Drone);
clearWeaponCargoGlobal (vestContainer Drone);
(vestContainer Drone) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",5];
(vestContainer Drone) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Drone) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Drone) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Drone);
clearMagazineCargoGlobal (uniformContainer Drone);
clearWeaponCargoGlobal (uniformContainer Drone);
(uniformContainer Drone) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Drone) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Drone) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Drone addWeapon "arifle_MX_F";
Drone addPrimaryWeaponItem "acc_pointer_IR";
Drone addPrimaryWeaponItem "optic_Aco";
(uniformContainer Drone) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Drone addWeapon "hgun_ACPC2_F";
Drone addWeapon "ItemRadio";
Drone selectWeapon (primaryWeapon Drone);
};

if (player == Mortier_tube) exitwith {
removeallweapons Mortier_tube;
removeallassigneditems Mortier_tube;
removeHeadgear Mortier_tube;
removeBackpack Mortier_tube;
removeVest Mortier_tube;

Mortier_tube addWeapon "ItemMap";
Mortier_tube addWeapon "ItemWatch";
Mortier_tube addWeapon "ItemCompass";
Mortier_tube addWeapon "H_HelmetB_grass";
Mortier_tube addWeapon "G_Sport_Checkered";
Mortier_tube addBackpack "B_Mortar_01_weapon_F";
Mortier_tube addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Mortier_tube);
clearMagazineCargoGlobal (vestContainer Mortier_tube);
clearWeaponCargoGlobal (vestContainer Mortier_tube);
(vestContainer Mortier_tube) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",5];
(vestContainer Mortier_tube) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Mortier_tube) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Mortier_tube) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Mortier_tube);
clearMagazineCargoGlobal (uniformContainer Mortier_tube);
clearWeaponCargoGlobal (uniformContainer Mortier_tube);
(uniformContainer Mortier_tube) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Mortier_tube) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Mortier_tube) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Mortier_tube addWeapon "arifle_MXC_F";
Mortier_tube addPrimaryWeaponItem "acc_pointer_IR";
Mortier_tube addPrimaryWeaponItem "optic_Aco";
(uniformContainer Mortier_tube) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Mortier_tube addWeapon "hgun_ACPC2_F";
Mortier_tube addWeapon "ItemRadio";
Mortier_tube selectWeapon (primaryWeapon Mortier_tube);
};

if (player == Sergent) exitwith {
removeallweapons Sergent;
removeallassigneditems Sergent;
removeHeadgear Sergent;
removeBackpack Sergent;
removeVest Sergent;

Sergent addWeapon "ItemMap";
Sergent addWeapon "ItemWatch";
Sergent addWeapon "ItemCompass";
Sergent addWeapon "ItemGPS";
Sergent addWeapon "H_MilCap_mcamo";
Sergent addWeapon "G_Tactical_Clear";
Sergent addWeapon "Binocular";
Sergent addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer Sergent);
clearMagazineCargoGlobal (vestContainer Sergent);
clearWeaponCargoGlobal (vestContainer Sergent);
(vestContainer Sergent) addmagazinecargoGlobal ["3Rnd_UGL_FlareWhite_F",2];
(vestContainer Sergent) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",7];
(vestContainer Sergent) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",2];
(vestContainer Sergent) addmagazinecargoGlobal ["Chemlight_green",1];
clearItemCargoGlobal (uniformContainer Sergent);
clearMagazineCargoGlobal (uniformContainer Sergent);
clearWeaponCargoGlobal (uniformContainer Sergent);
(uniformContainer Sergent) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Sergent) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Sergent) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Sergent addWeapon "arifle_MX_GL_F";
Sergent addPrimaryWeaponItem "acc_pointer_IR";
Sergent addPrimaryWeaponItem "optic_Hamr";
(uniformContainer Sergent) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Sergent addWeapon "hgun_ACPC2_F";
Sergent addWeapon "ItemRadio";
Sergent selectWeapon (primaryWeapon Sergent);
};

if (player == Sniper) exitwith {
removeallweapons Sniper;
removeallassigneditems Sniper;
removeHeadgear Sniper;
removeBackpack Sniper;
removeVest Sniper;

Sniper addWeapon "ItemMap";
Sniper addWeapon "ItemWatch";
Sniper addWeapon "ItemCompass";
Sniper addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Sniper);
clearMagazineCargoGlobal (vestContainer Sniper);
clearWeaponCargoGlobal (vestContainer Sniper);
(vestContainer Sniper) addmagazinecargoGlobal ["7Rnd_408_Mag",9];
(vestContainer Sniper) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Sniper) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Sniper);
clearMagazineCargoGlobal (uniformContainer Sniper);
clearWeaponCargoGlobal (uniformContainer Sniper);
(uniformContainer Sniper) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Sniper) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
(uniformContainer Sniper) addmagazinecargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",2];
(vestContainer Sniper) addmagazinecargoGlobal ["7Rnd_408_Mag",1];
Sniper addWeapon "srifle_LRR_F";
Sniper addPrimaryWeaponItem "acc_pointer_IR";
Sniper addPrimaryWeaponItem "optic_SOS";
(uniformContainer Sniper) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
Sniper addWeapon "hgun_P07_F";
Sniper addHandgunItem "muzzle_snds_L";
Sniper addWeapon "ItemRadio";
Sniper selectWeapon (primaryWeapon Sniper);
};

if (player == Observateur) exitwith {
removeallweapons Observateur;
removeallassigneditems Observateur;
removeHeadgear Observateur;
removeBackpack Observateur;
removeVest Observateur;

Observateur addWeapon "ItemMap";
Observateur addWeapon "ItemWatch";
Observateur addWeapon "ItemCompass";
Observateur addWeapon "Rangefinder";
Observateur addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Observateur);
clearMagazineCargoGlobal (vestContainer Observateur);
clearWeaponCargoGlobal (vestContainer Observateur);
(vestContainer Observateur) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",9];
(vestContainer Observateur) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Observateur) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Observateur) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Observateur);
clearMagazineCargoGlobal (uniformContainer Observateur);
clearWeaponCargoGlobal (uniformContainer Observateur);
(uniformContainer Observateur) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Observateur) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
(uniformContainer Observateur) addmagazinecargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",2];
(vestContainer Observateur) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Observateur addWeapon "arifle_MXM_F";
Observateur addPrimaryWeaponItem "acc_pointer_IR";
Observateur addPrimaryWeaponItem "muzzle_snds_H";
Observateur addPrimaryWeaponItem "optic_SOS";
(uniformContainer Observateur) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
Observateur addWeapon "hgun_P07_F";
Observateur addHandgunItem "muzzle_snds_L";
Observateur addWeapon "ItemRadio";
Observateur selectWeapon (primaryWeapon Observateur);
};

if (player == Appui_feu) exitwith {
removeallweapons Appui_feu;
removeallassigneditems Appui_feu;
removeHeadgear Appui_feu;
removeBackpack Appui_feu;
removeVest Appui_feu;

Appui_feu addWeapon "ItemMap";
Appui_feu addWeapon "ItemWatch";
Appui_feu addWeapon "ItemCompass";
Appui_feu addWeapon "H_HelmetB_grass";
Appui_feu addWeapon "G_Sport_Checkered";
Appui_feu addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Appui_feu);
clearMagazineCargoGlobal (vestContainer Appui_feu);
clearWeaponCargoGlobal (vestContainer Appui_feu);
(vestContainer Appui_feu) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",3];
(vestContainer Appui_feu) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Appui_feu) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Appui_feu) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Appui_feu);
clearMagazineCargoGlobal (uniformContainer Appui_feu);
clearWeaponCargoGlobal (uniformContainer Appui_feu);
(uniformContainer Appui_feu) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Appui_feu) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",3];
(vestContainer Appui_feu) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
Appui_feu addWeapon "LMG_Mk200_F";
Appui_feu addPrimaryWeaponItem "acc_pointer_IR";
Appui_feu addPrimaryWeaponItem "optic_Holosight";
(uniformContainer Appui_feu) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
Appui_feu addWeapon "hgun_Pistol_heavy_01_F";
Appui_feu addWeapon "ItemRadio";
Appui_feu selectWeapon (primaryWeapon Appui_feu);
};

if (player == Fusiller) exitwith {
removeallweapons Fusiller;
removeallassigneditems Fusiller;
removeHeadgear Fusiller;
removeBackpack Fusiller;
removeVest Fusiller;

Fusiller addWeapon "ItemMap";
Fusiller addWeapon "ItemWatch";
Fusiller addWeapon "ItemCompass";
Fusiller addWeapon "H_HelmetB_grass";
Fusiller addWeapon "G_Sport_Checkered";
Fusiller addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Fusiller);
clearMagazineCargoGlobal (vestContainer Fusiller);
clearWeaponCargoGlobal (vestContainer Fusiller);
(vestContainer Fusiller) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",9];
(vestContainer Fusiller) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Fusiller) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Fusiller) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Fusiller);
clearMagazineCargoGlobal (uniformContainer Fusiller);
clearWeaponCargoGlobal (uniformContainer Fusiller);
(uniformContainer Fusiller) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Fusiller) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Fusiller) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Fusiller addWeapon "arifle_MX_F";
Fusiller addPrimaryWeaponItem "acc_pointer_IR";
Fusiller addPrimaryWeaponItem "optic_Aco";
(uniformContainer Fusiller) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Fusiller addWeapon "hgun_ACPC2_F";
Fusiller addWeapon "ItemRadio";
Fusiller selectWeapon (primaryWeapon Fusiller);
};

if (player == Caporal) exitwith {
removeallweapons Caporal;
removeallassigneditems Caporal;
removeHeadgear Caporal;
removeBackpack Caporal;
removeVest Caporal;

Caporal addWeapon "ItemMap";
Caporal addWeapon "ItemWatch";
Caporal addWeapon "ItemCompass";
Caporal addWeapon "ItemGPS";
Caporal addWeapon "H_HelmetSpecB_paint1";
Caporal addWeapon "G_Tactical_Clear";
Caporal addWeapon "Binocular";
Caporal addVest "V_PlateCarrierH_CTRG";
clearItemCargoGlobal (vestContainer Caporal);
clearMagazineCargoGlobal (vestContainer Caporal);
clearWeaponCargoGlobal (vestContainer Caporal);
(vestContainer Caporal) addmagazinecargoGlobal ["3Rnd_UGL_FlareWhite_F",2];
(vestContainer Caporal) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",7];
(vestContainer Caporal) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",2];
(vestContainer Caporal) addmagazinecargoGlobal ["Chemlight_green",1];
clearItemCargoGlobal (uniformContainer Caporal);
clearMagazineCargoGlobal (uniformContainer Caporal);
clearWeaponCargoGlobal (uniformContainer Caporal);
(uniformContainer Caporal) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Caporal) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Caporal) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Caporal addWeapon "arifle_MX_GL_F";
Caporal addPrimaryWeaponItem "acc_pointer_IR";
Caporal addPrimaryWeaponItem "optic_Hamr";
(uniformContainer Caporal) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Caporal addWeapon "hgun_ACPC2_F";
Caporal addWeapon "ItemRadio";
Caporal selectWeapon (primaryWeapon Caporal);
};

if (player == Soldat_AT) exitwith {
removeallweapons Soldat_AT;
removeallassigneditems Soldat_AT;
removeHeadgear Soldat_AT;
removeBackpack Soldat_AT;
removeVest Soldat_AT;

Soldat_AT addWeapon "ItemMap";
Soldat_AT addWeapon "ItemWatch";
Soldat_AT addWeapon "ItemCompass";
Soldat_AT addWeapon "H_HelmetB_grass";
Soldat_AT addWeapon "G_Sport_Checkered";
Soldat_AT addBackpack "B_AssaultPack_Kerry";
clearItemCargoGlobal (backpackContainer Soldat_AT);
clearMagazineCargoGlobal (backpackContainer Soldat_AT);
clearWeaponCargoGlobal (backpackContainer Soldat_AT);
(backpackContainer Soldat_AT) addmagazinecargoGlobal ["Titan_AP",2];
Soldat_AT addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Soldat_AT);
clearMagazineCargoGlobal (vestContainer Soldat_AT);
clearWeaponCargoGlobal (vestContainer Soldat_AT);
(vestContainer Soldat_AT) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",4];
(vestContainer Soldat_AT) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Soldat_AT) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Soldat_AT) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Soldat_AT);
clearMagazineCargoGlobal (uniformContainer Soldat_AT);
clearWeaponCargoGlobal (uniformContainer Soldat_AT);
(uniformContainer Soldat_AT) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Soldat_AT) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Soldat_AT) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Soldat_AT addWeapon "arifle_MX_F";
Soldat_AT addPrimaryWeaponItem "acc_pointer_IR";
Soldat_AT addPrimaryWeaponItem "optic_Aco";
(backpackContainer Soldat_AT) addmagazinecargoGlobal ["Titan_AP",1];
Soldat_AT addWeapon "launch_B_Titan_short_F";
(uniformContainer Soldat_AT) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Soldat_AT addWeapon "hgun_ACPC2_F";
Soldat_AT addWeapon "ItemRadio";
Soldat_AT selectWeapon (primaryWeapon Soldat_AT);
};

if (player == Infirmier) exitwith {
removeallweapons Infirmier;
removeallassigneditems Infirmier;
removeHeadgear Infirmier;
removeBackpack Infirmier;
removeVest Infirmier;

Infirmier addWeapon "ItemMap";
Infirmier addWeapon "ItemWatch";
Infirmier addWeapon "ItemCompass";
Infirmier addWeapon "H_HelmetB_grass";
Infirmier addWeapon "G_Sport_Checkered";
Infirmier addBackpack "B_AssaultPack_Kerry";
clearItemCargoGlobal (backpackContainer Infirmier);
clearMagazineCargoGlobal (backpackContainer Infirmier);
clearWeaponCargoGlobal (backpackContainer Infirmier);
(backpackContainer Infirmier) additemcargoGlobal ["FirstAidKit",10];
(backpackContainer Infirmier) additemcargoGlobal ["Medikit",1];
Infirmier addVest "V_HarnessO_brn";
clearItemCargoGlobal (vestContainer Infirmier);
clearMagazineCargoGlobal (vestContainer Infirmier);
clearWeaponCargoGlobal (vestContainer Infirmier);
(vestContainer Infirmier) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",5];
(vestContainer Infirmier) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Infirmier) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Infirmier) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Infirmier);
clearMagazineCargoGlobal (uniformContainer Infirmier);
clearWeaponCargoGlobal (uniformContainer Infirmier);
(uniformContainer Infirmier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Infirmier) addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",1];
Infirmier addWeapon "arifle_MX_F";
Infirmier addPrimaryWeaponItem "acc_pointer_IR";
Infirmier addPrimaryWeaponItem "optic_Aco";
(uniformContainer Infirmier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Infirmier addWeapon "hgun_ACPC2_F";
Infirmier addWeapon "ItemRadio";
Infirmier selectWeapon (primaryWeapon Infirmier);
};

if (player == Chef) exitwith {
removeallweapons Chef;
removeallassigneditems Chef;
removeHeadgear Chef;
removeBackpack Chef;
removeVest Chef;

Chef addWeapon "ItemMap";
Chef addWeapon "ItemWatch";
Chef addWeapon "ItemCompass";
Chef addWeapon "ItemGPS";
Chef addWeapon "H_MilCap_dgtl";
Chef addWeapon "Binocular";
Chef addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Chef);
clearMagazineCargoGlobal (vestContainer Chef);
clearWeaponCargoGlobal (vestContainer Chef);
(vestContainer Chef) addmagazinecargoGlobal ["3Rnd_UGL_FlareWhite_F",2];
(vestContainer Chef) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",7];
(vestContainer Chef) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",2];
(vestContainer Chef) addmagazinecargoGlobal ["Chemlight_green",1];
clearItemCargoGlobal (uniformContainer Chef);
clearMagazineCargoGlobal (uniformContainer Chef);
clearWeaponCargoGlobal (uniformContainer Chef);
(uniformContainer Chef) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Chef) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Chef) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Chef addWeapon "arifle_Mk20_GL_F";
Chef addPrimaryWeaponItem "acc_pointer_IR";
Chef addPrimaryWeaponItem "optic_Hamr";
(uniformContainer Chef) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Chef addWeapon "hgun_ACPC2_F";
Chef addWeapon "ItemRadio";
Chef selectWeapon (primaryWeapon Chef);
};

if (player == Soldat) exitwith {
removeallweapons Soldat;
removeallassigneditems Soldat;
removeHeadgear Soldat;
removeBackpack Soldat;
removeVest Soldat;

Soldat addWeapon "ItemMap";
Soldat addWeapon "ItemWatch";
Soldat addWeapon "ItemCompass";
Soldat addWeapon "H_HelmetIA_camo";
Soldat addWeapon "G_Shades_Black";
Soldat addVest "V_Chestrig_oli";
clearItemCargoGlobal (vestContainer Soldat);
clearMagazineCargoGlobal (vestContainer Soldat);
clearWeaponCargoGlobal (vestContainer Soldat);
(vestContainer Soldat) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",9];
(vestContainer Soldat) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Soldat) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Soldat) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Soldat);
clearMagazineCargoGlobal (uniformContainer Soldat);
clearWeaponCargoGlobal (uniformContainer Soldat);
(uniformContainer Soldat) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Soldat) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Soldat) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Soldat addWeapon "arifle_Mk20_F";
Soldat addPrimaryWeaponItem "acc_pointer_IR";
Soldat addPrimaryWeaponItem "optic_Aco";
(uniformContainer Soldat) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Soldat addWeapon "hgun_ACPC2_F";
Soldat addWeapon "ItemRadio";
Soldat selectWeapon (primaryWeapon Soldat);
};

if (player == Medic) exitwith {
removeallweapons Medic;
removeallassigneditems Medic;
removeHeadgear Medic;
removeBackpack Medic;
removeVest Medic;

Medic addWeapon "ItemMap";
Medic addWeapon "ItemWatch";
Medic addWeapon "ItemCompass";
Medic addWeapon "H_HelmetIA_camo";
Medic addWeapon "G_Shades_Black";
Medic addBackpack "B_FieldPack_oli";
clearItemCargoGlobal (backpackContainer Medic);
clearMagazineCargoGlobal (backpackContainer Medic);
clearWeaponCargoGlobal (backpackContainer Medic);
(backpackContainer Medic) additemcargoGlobal ["FirstAidKit",10];
(backpackContainer Medic) additemcargoGlobal ["Medikit",1];
Medic addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer Medic);
clearMagazineCargoGlobal (vestContainer Medic);
clearWeaponCargoGlobal (vestContainer Medic);
(vestContainer Medic) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",5];
(vestContainer Medic) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Medic) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Medic) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Medic);
clearMagazineCargoGlobal (uniformContainer Medic);
clearWeaponCargoGlobal (uniformContainer Medic);
(uniformContainer Medic) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Medic) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Medic addWeapon "arifle_Mk20_F";
Medic addPrimaryWeaponItem "acc_pointer_IR";
Medic addPrimaryWeaponItem "optic_Aco";
(uniformContainer Medic) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Medic addWeapon "hgun_ACPC2_F";
Medic addWeapon "ItemRadio";
Medic selectWeapon (primaryWeapon Medic);
};

if (player == Appui) exitwith {
removeallweapons Appui;
removeallassigneditems Appui;
removeHeadgear Appui;
removeBackpack Appui;
removeVest Appui;

Appui addWeapon "ItemMap";
Appui addWeapon "ItemWatch";
Appui addWeapon "ItemCompass";
Appui addWeapon "H_HelmetIA_camo";
Appui addWeapon "G_Shades_Black";
Appui addVest "V_HarnessO_gry";
clearItemCargoGlobal (vestContainer Appui);
clearMagazineCargoGlobal (vestContainer Appui);
clearWeaponCargoGlobal (vestContainer Appui);
(vestContainer Appui) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",3];
(vestContainer Appui) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Appui) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Appui) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Appui);
clearMagazineCargoGlobal (uniformContainer Appui);
clearWeaponCargoGlobal (uniformContainer Appui);
(uniformContainer Appui) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Appui) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",3];
(vestContainer Appui) addmagazinecargoGlobal ["200Rnd_65x39_cased_Box_Tracer",1];
Appui addWeapon "LMG_Mk200_F";
Appui addPrimaryWeaponItem "acc_pointer_IR";
Appui addPrimaryWeaponItem "optic_Holosight";
(uniformContainer Appui) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",1];
Appui addWeapon "hgun_Pistol_heavy_02_F";
Appui addWeapon "ItemRadio";
Appui selectWeapon (primaryWeapon Appui);
};

if (player == Antichar) exitwith {
removeallweapons Antichar;
removeallassigneditems Antichar;
removeHeadgear Antichar;
removeBackpack Antichar;
removeVest Antichar;

Antichar addWeapon "ItemMap";
Antichar addWeapon "ItemWatch";
Antichar addWeapon "ItemCompass";
Antichar addWeapon "H_HelmetIA_camo";
Antichar addWeapon "G_Shades_Black";
Antichar addBackpack "B_FieldPack_oli";
clearItemCargoGlobal (backpackContainer Antichar);
clearMagazineCargoGlobal (backpackContainer Antichar);
clearWeaponCargoGlobal (backpackContainer Antichar);
(backpackContainer Antichar) addmagazinecargoGlobal ["Titan_AP",2];
Antichar addVest "V_BandollierB_oli";
clearItemCargoGlobal (vestContainer Antichar);
clearMagazineCargoGlobal (vestContainer Antichar);
clearWeaponCargoGlobal (vestContainer Antichar);
(vestContainer Antichar) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(vestContainer Antichar) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Antichar) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Antichar) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Antichar);
clearMagazineCargoGlobal (uniformContainer Antichar);
clearWeaponCargoGlobal (uniformContainer Antichar);
(uniformContainer Antichar) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Antichar) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Antichar) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Antichar addWeapon "arifle_Mk20_F";
Antichar addPrimaryWeaponItem "acc_pointer_IR";
Antichar addPrimaryWeaponItem "optic_Aco";
(backpackContainer Antichar) addmagazinecargoGlobal ["Titan_AP",1];
Antichar addWeapon "launch_I_Titan_short_F";
(uniformContainer Antichar) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Antichar addWeapon "hgun_ACPC2_F";
Antichar addWeapon "ItemRadio";
Antichar selectWeapon (primaryWeapon Antichar);
};

if (player == Officier) exitwith {
removeallweapons Officier;
removeallassigneditems Officier;
removeHeadgear Officier;
removeBackpack Officier;
removeVest Officier;

Officier addWeapon "ItemMap";
Officier addWeapon "ItemWatch";
Officier addWeapon "ItemCompass";
Officier addWeapon "ItemGPS";
Officier addWeapon "H_HelmetIA_camo";
Officier addWeapon "Binocular";
Officier addVest "V_PlateCarrier1_rgr";
clearItemCargoGlobal (vestContainer Officier);
clearMagazineCargoGlobal (vestContainer Officier);
clearWeaponCargoGlobal (vestContainer Officier);
(vestContainer Officier) addmagazinecargoGlobal ["3Rnd_UGL_FlareWhite_F",2];
(vestContainer Officier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",7];
(vestContainer Officier) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",2];
(vestContainer Officier) addmagazinecargoGlobal ["Chemlight_green",1];
clearItemCargoGlobal (uniformContainer Officier);
clearMagazineCargoGlobal (uniformContainer Officier);
clearWeaponCargoGlobal (uniformContainer Officier);
(uniformContainer Officier) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Officier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Officier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Officier addWeapon "arifle_Mk20_GL_F";
Officier addPrimaryWeaponItem "acc_pointer_IR";
Officier addPrimaryWeaponItem "optic_Hamr";
(uniformContainer Officier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Officier addWeapon "hgun_ACPC2_F";
Officier addWeapon "ItemRadio";
Officier selectWeapon (primaryWeapon Officier);
};

if (player == UAV) exitwith {
removeallweapons UAV;
removeallassigneditems UAV;
removeHeadgear UAV;
removeBackpack UAV;
removeVest UAV;

UAV addWeapon "ItemMap";
UAV addWeapon "ItemWatch";
UAV addWeapon "ItemCompass";
UAV addWeapon "I_UavTerminal";
UAV addWeapon "H_HelmetIA_camo";
UAV addWeapon "G_Shades_Black";
UAV addBackpack "B_UAV_01_backpack_F";
UAV addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer UAV);
clearMagazineCargoGlobal (vestContainer UAV);
clearWeaponCargoGlobal (vestContainer UAV);
(vestContainer UAV) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",5];
(vestContainer UAV) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer UAV) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer UAV) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer UAV);
clearMagazineCargoGlobal (uniformContainer UAV);
clearWeaponCargoGlobal (uniformContainer UAV);
(uniformContainer UAV) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer UAV) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer UAV) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
UAV addWeapon "arifle_Mk20C_F";
UAV addPrimaryWeaponItem "acc_pointer_IR";
UAV addPrimaryWeaponItem "optic_Aco";
(uniformContainer UAV) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
UAV addWeapon "hgun_ACPC2_F";
UAV addWeapon "ItemRadio";
UAV selectWeapon (primaryWeapon UAV);
};

if (player == Mortier) exitwith {
removeallweapons Mortier;
removeallassigneditems Mortier;
removeHeadgear Mortier;
removeBackpack Mortier;
removeVest Mortier;

Mortier addWeapon "ItemMap";
Mortier addWeapon "ItemWatch";
Mortier addWeapon "ItemCompass";
Mortier addWeapon "H_HelmetIA_camo";
Mortier addWeapon "G_Shades_Black";
Mortier addBackpack "B_Mortar_01_weapon_F";
Mortier addVest "V_BandollierB_oli";
clearItemCargoGlobal (vestContainer Mortier);
clearMagazineCargoGlobal (vestContainer Mortier);
clearWeaponCargoGlobal (vestContainer Mortier);
(vestContainer Mortier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(vestContainer Mortier) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Mortier) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Mortier) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Mortier);
clearMagazineCargoGlobal (uniformContainer Mortier);
clearWeaponCargoGlobal (uniformContainer Mortier);
(uniformContainer Mortier) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Mortier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Mortier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Mortier addWeapon "arifle_Mk20C_F";
Mortier addPrimaryWeaponItem "acc_pointer_IR";
Mortier addPrimaryWeaponItem "optic_Aco";
(uniformContainer Mortier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Mortier addWeapon "hgun_ACPC2_F";
Mortier addWeapon "ItemRadio";
Mortier selectWeapon (primaryWeapon Mortier);
};

if (player == Trepier) exitwith {
removeallweapons Trepier;
removeallassigneditems Trepier;
removeHeadgear Trepier;
removeBackpack Trepier;
removeVest Trepier;

Trepier addWeapon "ItemMap";
Trepier addWeapon "ItemWatch";
Trepier addWeapon "ItemCompass";
Trepier addWeapon "H_HelmetIA_camo";
Trepier addWeapon "G_Shades_Black";
Trepier addWeapon "Rangefinder";
Trepier addBackpack "B_Mortar_01_support_F";
Trepier addVest "V_BandollierB_oli";
clearItemCargoGlobal (vestContainer Trepier);
clearMagazineCargoGlobal (vestContainer Trepier);
clearWeaponCargoGlobal (vestContainer Trepier);
(vestContainer Trepier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(vestContainer Trepier) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Trepier) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Trepier) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Trepier);
clearMagazineCargoGlobal (uniformContainer Trepier);
clearWeaponCargoGlobal (uniformContainer Trepier);
(uniformContainer Trepier) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Trepier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer Trepier) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Trepier addWeapon "arifle_Mk20C_F";
Trepier addPrimaryWeaponItem "acc_pointer_IR";
Trepier addPrimaryWeaponItem "optic_Aco";
(uniformContainer Trepier) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Trepier addWeapon "hgun_ACPC2_F";
Trepier addWeapon "ItemRadio";
Trepier selectWeapon (primaryWeapon Trepier);
};

if (player == Observator) exitwith {
removeallweapons Observator;
removeallassigneditems Observator;
removeHeadgear Observator;
removeBackpack Observator;
removeVest Observator;

Observator addWeapon "ItemMap";
Observator addWeapon "ItemWatch";
Observator addWeapon "ItemCompass";
Observator addWeapon "Rangefinder";
Observator addVest "V_HarnessO_gry";
clearItemCargoGlobal (vestContainer Observator);
clearMagazineCargoGlobal (vestContainer Observator);
clearWeaponCargoGlobal (vestContainer Observator);
(vestContainer Observator) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",9];
(vestContainer Observator) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Observator) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer Observator) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Observator);
clearMagazineCargoGlobal (uniformContainer Observator);
clearWeaponCargoGlobal (uniformContainer Observator);
(uniformContainer Observator) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Observator) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
(uniformContainer Observator) addmagazinecargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",2];
(vestContainer Observator) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",1];
Observator addWeapon "arifle_Katiba_F";
Observator addPrimaryWeaponItem "acc_pointer_IR";
Observator addPrimaryWeaponItem "muzzle_snds_H";
Observator addPrimaryWeaponItem "optic_SOS";
(uniformContainer Observator) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
Observator addWeapon "hgun_P07_F";
Observator addHandgunItem "muzzle_snds_L";
Observator addWeapon "ItemRadio";
Observator selectWeapon (primaryWeapon Observator);
};

if (player == Snip) exitwith {
removeallweapons Snip;
removeallassigneditems Snip;
removeHeadgear Snip;
removeBackpack Snip;
removeVest Snip;

Snip addWeapon "ItemMap";
Snip addWeapon "ItemWatch";
Snip addWeapon "ItemCompass";
Snip addVest "V_HarnessO_gry";
clearItemCargoGlobal (vestContainer Snip);
clearMagazineCargoGlobal (vestContainer Snip);
clearWeaponCargoGlobal (vestContainer Snip);
(vestContainer Snip) addmagazinecargoGlobal ["7Rnd_408_Mag",9];
(vestContainer Snip) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer Snip) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer Snip);
clearMagazineCargoGlobal (uniformContainer Snip);
clearWeaponCargoGlobal (uniformContainer Snip);
(uniformContainer Snip) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer Snip) addmagazinecargoGlobal ["16Rnd_9x21_Mag",3];
(uniformContainer Snip) addmagazinecargoGlobal ["ClaymoreDirectionalMine_Remote_Mag",2];
(vestContainer Snip) addmagazinecargoGlobal ["7Rnd_408_Mag",1];
Snip addWeapon "srifle_LRR_F";
Snip addPrimaryWeaponItem "acc_pointer_IR";
Snip addPrimaryWeaponItem "optic_SOS";
(uniformContainer Snip) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
Snip addWeapon "hgun_P07_F";
Snip addHandgunItem "muzzle_snds_L";
Snip addWeapon "ItemRadio";
Snip selectWeapon (primaryWeapon Snip);
};

if (player == unit_35_64) exitwith {
removeallweapons unit_35_64;
removeallassigneditems unit_35_64;
removeHeadgear unit_35_64;
removeBackpack unit_35_64;
removeVest unit_35_64;

unit_35_64 addWeapon "ItemMap";
unit_35_64 addWeapon "ItemWatch";
unit_35_64 addWeapon "ItemCompass";
unit_35_64 addWeapon "H_HelmetCrew_B";
unit_35_64 addWeapon "G_Sport_Checkered";
unit_35_64 addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer unit_35_64);
clearMagazineCargoGlobal (vestContainer unit_35_64);
clearWeaponCargoGlobal (vestContainer unit_35_64);
(vestContainer unit_35_64) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",9];
(vestContainer unit_35_64) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer unit_35_64) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer unit_35_64) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer unit_35_64);
clearMagazineCargoGlobal (uniformContainer unit_35_64);
clearWeaponCargoGlobal (uniformContainer unit_35_64);
(uniformContainer unit_35_64) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer unit_35_64) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer unit_35_64) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",1];
unit_35_64 addWeapon "SMG_01_F";
unit_35_64 addPrimaryWeaponItem "acc_pointer_IR";
unit_35_64 addPrimaryWeaponItem "optic_Aco";
(uniformContainer unit_35_64) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
unit_35_64 addWeapon "hgun_ACPC2_F";
unit_35_64 addWeapon "ItemRadio";
unit_35_64 selectWeapon (primaryWeapon unit_35_64);
};

if (player == unit_35_65) exitwith {
removeallweapons unit_35_65;
removeallassigneditems unit_35_65;
removeHeadgear unit_35_65;
removeBackpack unit_35_65;
removeVest unit_35_65;

unit_35_65 addWeapon "ItemMap";
unit_35_65 addWeapon "ItemWatch";
unit_35_65 addWeapon "ItemCompass";
unit_35_65 addWeapon "H_HelmetCrew_B";
unit_35_65 addWeapon "G_Sport_Checkered";
unit_35_65 addVest "V_Chestrig_rgr";
clearItemCargoGlobal (vestContainer unit_35_65);
clearMagazineCargoGlobal (vestContainer unit_35_65);
clearWeaponCargoGlobal (vestContainer unit_35_65);
(vestContainer unit_35_65) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",9];
(vestContainer unit_35_65) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer unit_35_65) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer unit_35_65) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer unit_35_65);
clearMagazineCargoGlobal (uniformContainer unit_35_65);
clearWeaponCargoGlobal (uniformContainer unit_35_65);
(uniformContainer unit_35_65) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer unit_35_65) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer unit_35_65) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",1];
unit_35_65 addWeapon "SMG_01_F";
unit_35_65 addPrimaryWeaponItem "acc_pointer_IR";
unit_35_65 addPrimaryWeaponItem "optic_Aco";
(uniformContainer unit_35_65) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
unit_35_65 addWeapon "hgun_ACPC2_F";
unit_35_65 addWeapon "ItemRadio";
unit_35_65 selectWeapon (primaryWeapon unit_35_65);
};

if (player == unit_36_65) exitwith {
removeallweapons unit_36_65;
removeallassigneditems unit_36_65;
removeHeadgear unit_36_65;
removeBackpack unit_36_65;
removeVest unit_36_65;

unit_36_65 addWeapon "ItemMap";
unit_36_65 addWeapon "ItemWatch";
unit_36_65 addWeapon "ItemCompass";
unit_36_65 addWeapon "H_HelmetCrew_B";
unit_36_65 addWeapon "G_Shades_Black";
unit_36_65 addVest "V_Chestrig_oli";
clearItemCargoGlobal (vestContainer unit_36_65);
clearMagazineCargoGlobal (vestContainer unit_36_65);
clearWeaponCargoGlobal (vestContainer unit_36_65);
(vestContainer unit_36_65) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",9];
(vestContainer unit_36_65) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer unit_36_65) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer unit_36_65) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer unit_36_65);
clearMagazineCargoGlobal (uniformContainer unit_36_65);
clearWeaponCargoGlobal (uniformContainer unit_36_65);
(uniformContainer unit_36_65) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer unit_36_65) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer unit_36_65) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",1];
unit_36_65 addWeapon "SMG_01_F";
unit_36_65 addPrimaryWeaponItem "acc_pointer_IR";
unit_36_65 addPrimaryWeaponItem "optic_Aco";
(uniformContainer unit_36_65) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
unit_36_65 addWeapon "hgun_ACPC2_F";
unit_36_65 addWeapon "ItemRadio";
unit_36_65 selectWeapon (primaryWeapon unit_36_65);
};

if (player == unit_36_66) exitwith {
removeallweapons unit_36_66;
removeallassigneditems unit_36_66;
removeHeadgear unit_36_66;
removeBackpack unit_36_66;
removeVest unit_36_66;

unit_36_66 addWeapon "ItemMap";
unit_36_66 addWeapon "ItemWatch";
unit_36_66 addWeapon "ItemCompass";
unit_36_66 addWeapon "H_HelmetCrew_B";
unit_36_66 addWeapon "G_Shades_Black";
unit_36_66 addVest "V_Chestrig_oli";
clearItemCargoGlobal (vestContainer unit_36_66);
clearMagazineCargoGlobal (vestContainer unit_36_66);
clearWeaponCargoGlobal (vestContainer unit_36_66);
(vestContainer unit_36_66) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",9];
(vestContainer unit_36_66) addmagazinecargoGlobal ["SmokeShell",2];
(vestContainer unit_36_66) addmagazinecargoGlobal ["HandGrenade",2];
(vestContainer unit_36_66) addmagazinecargoGlobal ["Chemlight_green",2];
clearItemCargoGlobal (uniformContainer unit_36_66);
clearMagazineCargoGlobal (uniformContainer unit_36_66);
clearWeaponCargoGlobal (uniformContainer unit_36_66);
(uniformContainer unit_36_66) additemcargoGlobal ["FirstAidKit",1];
(uniformContainer unit_36_66) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",3];
(vestContainer unit_36_66) addmagazinecargoGlobal ["30Rnd_45ACP_Mag_SMG_01",1];
unit_36_66 addWeapon "SMG_01_F";
unit_36_66 addPrimaryWeaponItem "acc_pointer_IR";
unit_36_66 addPrimaryWeaponItem "optic_Aco";
(uniformContainer unit_36_66) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
unit_36_66 addWeapon "hgun_ACPC2_F";
unit_36_66 addWeapon "ItemRadio";
unit_36_66 selectWeapon (primaryWeapon unit_36_66);
};

